### ISSUE TITLE
'numpy' has no attribute 'object'

### ISSUE THREAD

**Issue by SimonOuellette35** [deepmind/dm_alchemy#11]
I am now attempting to initialize a symbolic environment, with the following code:

```
from dm_alchemy import symbolic_alchemy

level_name = 'alchemy/perceptual_mapping_randomized_with_rotation_and_random_bottleneck'
env = symbolic_alchemy.get_symbolic_alchemy_level(level_name, seed=314)
```
I receive the error:

> anaconda3/envs/lib/python3.11/site-packages/dm_alchemy/ideal_observer/precomputed_maps.py:802: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
>   dtype=np.object)
> Traceback (most recent call last):
>   File "trainAlchemy.py", line 9, in <module>
>     env = symbolic_alchemy.get_symbolic_alchemy_level(level_name, seed=314)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "anaconda3/envs/lib/python3.11/site-packages/dm_alchemy/symbolic_alchemy.py", line 867, in get_symbolic_alchemy_level
>     _, index_to_perm_index = precomputed_maps.get_perm_index_conversion()
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "anaconda3/envs/lib/python3.11/site-packages/dm_alchemy/ideal_observer/precomputed_maps.py", line 802, in get_perm_index_conversion
>     dtype=np.object)
>           ^^^^^^^^^
>   File "anaconda3/envs/lib/python3.11/site-packages/numpy/\_\_init\_\_.py", line 284, in \_\_getattr\_\_
>     raise AttributeError("module {!r} has no attribute "
> AttributeError: module 'numpy' has no attribute 'object'. Did you mean: 'object\_'?

**Comment by SimonOuellette35** [comment]
I just pulled the updates, pip installed again, and I'm getting a different error:

> "trainAlchemy.py", line 6, in <module>
> print(env.observation_spec())
>         ^^^^^^^^^^^^^^^^^^^^^^
>  File "/home/simon/anaconda3/envs/ConvictionPlanner/lib/python3.11/site-packages/dm_alchemy/symbolic_alchemy.py", line > 500, in observation_spec
>    'symbolic_obs': specs.Array(shape=(obs_features,), dtype=float32,
>                                                             ^^^^^^^
> NameError: name 'float32' is not defined. Did you mean: 'float'?

Is it related? It occurs when I try to print the observation specifications. (which means the environment initialization does work, by the way)

**Comment by MichaelJKing** [comment]
Sorry about that. I have fixed the last commit so it should be okay if you check out the updated commit. I have run the AlchemyGettingStarted.ipynb notebook and this all runs successfully so hopefully you won't have further issues.

**Comment by SimonOuellette35** [comment]
Great! Problem fixed, thank you.
