### ISSUE TITLE
Getting a more friendly graph from input_chem

### ISSUE THREAD

**Issue by arcosin** [deepmind/dm_alchemy#12]
Hello,
I really like this environment!
One problem i've had though is to do with the ground truth chemistry we can get from timestep.observation['input_chem'].
I understand why it is structured the way it is, as it is more tied to the chemistry formulation in the paper, but it's not very easy to work with for the purposes I have. Especially as the lookup tables for the actual potion colors and stone states are not mentioned in documentation.
Is there an easy built-in way to convert this chemistry to an adjacency matrix or some other representation that is more friendly? With the actual potion colors and stone attributes maintained if possible. 
Thanks!

**Comment by janexwang** [comment]
Hi, thanks for your comment!

You can actually get a nicer version of the chemistry by accessing the environment's private attribute `env._chemistry`, which will give you potion_map, stone_map, and graph in ways that are more intuitive to deal with. The graph then has an edge list and a node list which would be equivalent to an adjacency graph.

If you're interested in how the latent coordinates (found in the nodes) are converted into the perceived stones and potions, you can use the functions in `types/stones_and_potions.py`. 

You can see how the perceived attributes of stones and potions are translated into physical appearance by checking out `unity_python_conversion.py`.

Hope this helps!
Jane

**Comment by arcosin** [comment]
Thanks!
