### ISSUE TITLE
Access to the source code of the environment?

### ISSUE THREAD

**Issue by eleninisioti** [deepmind/dm_alchemy#13]
Hello, I see the environment is loaded as a docker container and I was wondering how one can get access to the source code. Another question I have is whether one can get a vectorised version.

**Comment by janexwang** [comment]
Sorry, we're only able to provide the docker version of the full Alchemy task. There is a symbolic version however, if that's what you mean by "vectorised"? The tutorial colab tells you how to load up the symbolic version which provides observations in a symbolic format (vector of numbers).

**Comment by eleninisioti** [comment]
Thanks for the info!
