### ISSUE TITLE
Running IdealObserverBot

### ISSUE THREAD

**Issue by BKHMSI** [deepmind/dm_alchemy#3]
Hi, 
I am trying to replicate the evaluation of the _Ideal Observer_ agent on _Symbolic Alchemy_ to get the `~ 284.4 ± 1.6` score reported in the paper. That said, I wrote the following function in an attempt to do so:

Side note: I know that you made available the ideal observer evaluation trajectory in the `agent_events` folder, but my aim is to then use the IdealObserverBot on a different set of events. 

```python
def evaluate():

    level_name = "perceptual_mapping_randomized_with_random_bottleneck"
    chems = chemistries_proto_conversion.load_chemistries_and_items(
        f'chemistries/{level_name}/chemistries')

    precomputed = precomputed_maps.load_from_level_name(level_name)
    reward_weights = RewardWeights(coefficients=[1, 1, 1], offset=0, bonus=12)

    N_EPISODES = 1_000
    rewards = np.zeros(N_EPISODES)

    for ep in tqdm(range(N_EPISODES)):

        chem, items = chems[ep]
        env = symbolic_alchemy.get_symbolic_alchemy_fixed(chemistry=chem, episode_items=items)

        env.add_trackers({symbolic_alchemy_trackers.ScoreTracker.NAME: symbolic_alchemy_trackers.ScoreTracker(env._reward_weights)})

        belief_state_tracker = {symbolic_alchemy_trackers.BeliefStateTracker.NAME: symbolic_alchemy_trackers.BeliefStateTracker(precomputed, env)}
        env.add_trackers(belief_state_tracker)

        bot = IdealObserverBot(reward_weights, precomputed, env, minimise_world_states=False)

        episode_results = bot.run_episode()
    
        rewards[ep] = np.sum(episode_results['score']['per_trial'])

    return rewards.mean(), rewards.std() / np.sqrt(N_EPISODES)
 ```
 
Since each episode takes understandably a long time to run, I just want to confirm the correctness of my code as it's based on a few assumptions I took while reading the codebase. 

Thanks!

**Comment by MichaelJKing** [comment]
Hi,

The code looks reasonable to me. You might want to add an AddMatrixEventTracker as this will record the actions taken by the ideal observer so you can replay them later if you need to.

Running the ideal observer on all of the test episodes will be very slow though especially if you cannot parallelize across computers. Some episodes are much quicker than others as they require less search. If you are not comparing to an agent running on the 3D task you might be better off with episodes with fewer stones or potions each trial which can run much faster.

**Comment by BKHMSI** [comment]
Great, thanks for the advice!
